CREATE TABLE [tbl_Revisit_List_Test] (
  [ID] AUTOINCREMENT CONSTRAINT [ID] PRIMARY KEY  UNIQUE  NOT NULL ,
  [PARK] VARCHAR (255),
  [EcositeType] VARCHAR (255),
  [Plot] LONG ,
  [ParkPlot] VARCHAR (255)
)
