dbMemo "SQL" ="SELECT *\015\012FROM (SELECT L.Unit_Code AS Park, L.Plot_ID AS Plot, L.Vegetatio"
    "n_Type AS VegType, E.Start_Date AS VisitDate, LPBT.Transect AS Transect, \"Missi"
    "ng densiometer records (<5).\" AS Issue\015\012FROM (tbl_Locations L INNER JOIN "
    "(tbl_Events E INNER JOIN tbl_LP_Belt_Transect LPBT ON E.Event_ID = LPBT.Event_ID"
    ") ON L.Location_ID = E.Location_ID) INNER JOIN tbl_LP_Densiometer LPD ON LPBT.Tr"
    "ansect_ID = LPD.Transect_ID\015\012GROUP BY L.Unit_Code, L.Plot_ID, L.Vegetation"
    "_Type, E.Start_Date, LPBT.Transect\015\012HAVING L.Vegetation_Type = \"forest\" "
    "AND Count(LPD.SD_ID) < 5\015\012UNION \015\012SELECT L.Unit_Code AS Park, L.Plot"
    "_ID AS Plot, L.Vegetation_Type AS VegType, E.Start_Date AS VisitDate, LPBT.Trans"
    "ect AS Transect, \"Missing one or more densiometer readings.\" AS Issue\015\012F"
    "ROM (tbl_Locations L INNER JOIN (tbl_Events E INNER JOIN tbl_LP_Belt_Transect LP"
    "BT ON E.Event_ID = LPBT.Event_ID) ON L.Location_ID = E.Location_ID) INNER JOIN t"
    "bl_LP_Densiometer LPD ON LPBT.Transect_ID = LPD.Transect_ID\015\012WHERE (L.Vege"
    "tation_Type = \"forest\") AND \015\012(LPD.Total1 Is Null OR LPD.Total2 Is Null "
    "OR LPD.Total3 Is Null OR LPD.Total4 Is Null))  AS [%$##@_Alias]\015\012WHERE Par"
    "k = 'CEBR'\015\012AND Plot = 11\015\012AND VisitDate = #3/27/2019#;\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
Begin
End
