dbMemo "SQL" ="SELECT tbl_Locations.Unit_Code, tbl_Locations.Plot_ID, tbl_Locations.Vegetation_"
    "Type, tbl_Events.Start_Date, IIf([tlu_NCPN_Plants]![LU_Code] Is Null,[tbl_OT_Tre"
    "e_Saplings]![Species],[tlu_NCPN_Plants]![LU_Code]) AS Species_Code, tlu_NCPN_Pla"
    "nts.Utah_Species, tbl_OT_Tree_Saplings.Alive, tbl_OT_Tree_Saplings.D25, tbl_OT_T"
    "ree_Saplings.D51, tbl_OT_Tree_Saplings.D101\015\012FROM ((tbl_Locations INNER JO"
    "IN tbl_Events ON tbl_Locations.Location_ID = tbl_Events.Location_ID) INNER JOIN "
    "tbl_OT_Tree_Saplings ON tbl_Events.Event_ID = tbl_OT_Tree_Saplings.Event_ID) LEF"
    "T JOIN tlu_NCPN_Plants ON tbl_OT_Tree_Saplings.Species = tlu_NCPN_Plants.Master_"
    "PLANT_Code\015\012WHERE (tbl_OT_Tree_Saplings.D25 Is Null) \015\012OR (tbl_OT_Tr"
    "ee_Saplings.D51 Is Null) \015\012OR (tbl_OT_Tree_Saplings.D101 Is Null) \015\012"
    "OR ((tbl_OT_Tree_Saplings.D25=0) \015\012AND (tbl_OT_Tree_Saplings.D51=0) \015\012"
    "AND (tbl_OT_Tree_Saplings.D101=0))\015\012AND  tbl_Locations.Unit_Code = 'ARCH'\015"
    "\012AND tbl_Events.Start_Date = #3/31/2018#\015\012AND tbl_Locations.Plot_ID = 1"
    "\015\012ORDER BY tbl_Locations.Unit_Code, tbl_Locations.Plot_ID, tbl_Events.Star"
    "t_Date, IIf([tlu_NCPN_Plants]![LU_Code] Is Null,[tbl_OT_Tree_Saplings]![Species]"
    ",[tlu_NCPN_Plants]![LU_Code]), tbl_OT_Tree_Saplings.Alive;\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
Begin
End
