dbMemo "SQL" ="PARAMETERS pkcode Text ( 4 ), pid Long, vdate DateTime;\015\012SELECT tbl_Locati"
    "ons.Unit_Code, tbl_Locations.Plot_ID, tbl_Locations.Vegetation_Type, tbl_Events."
    "Start_Date, tbl_LP_Belt_Transect.Transect, IIf([tlu_NCPN_Plants]![LU_Code] Is Nu"
    "ll,[tbl_LP_Shrub]![Species],[tlu_NCPN_Plants]![LU_Code]) AS Species_Code, tlu_NC"
    "PN_Plants.Utah_Species, tbl_LP_Shrub.HC10, tbl_LP_Shrub.HC25, tbl_LP_Shrub.HC50,"
    " tbl_LP_Shrub.HC100, tbl_LP_Shrub.HC2m, tbl_LP_Shrub.HCGT2\015\012FROM tbl_Locat"
    "ions INNER JOIN (tbl_Events INNER JOIN (tbl_LP_Belt_Transect INNER JOIN (tbl_LP_"
    "Shrub LEFT JOIN tlu_NCPN_Plants ON tbl_LP_Shrub.Species = tlu_NCPN_Plants.Master"
    "_PLANT_Code) ON tbl_LP_Belt_Transect.Transect_ID = tbl_LP_Shrub.Transect_ID) ON "
    "tbl_Events.Event_ID = tbl_LP_Belt_Transect.Event_ID) ON tbl_Locations.Location_I"
    "D = tbl_Events.Location_ID\015\012WHERE (\015\012(tbl_LP_Shrub.HC10 Is Null) \015"
    "\012OR (tbl_LP_Shrub.HC25 Is Null) \015\012OR (tbl_LP_Shrub.HC50 Is Null) \015\012"
    "OR (tbl_LP_Shrub.HC100 Is Null) \015\012OR (tbl_LP_Shrub.HC2m Is Null) \015\012O"
    "R (tbl_LP_Shrub.HCGT2 Is Null) \015\012OR (\015\012(tbl_LP_Shrub.HC10=0) \015\012"
    "AND (tbl_LP_Shrub.HC25=0) \015\012AND (tbl_LP_Shrub.HC50=0) \015\012AND (tbl_LP_"
    "Shrub.HC100=0) \015\012AND (tbl_LP_Shrub.HC2m=0) \015\012AND (tbl_LP_Shrub.HCGT2"
    "=0)\015\012)\015\012)\015\012AND  tbl_Locations.Unit_Code = [pkcode]\015\012AND "
    "tbl_Events.Start_Date = [vdate]\015\012AND tbl_Locations.Plot_ID = [pid]\015\012"
    "ORDER BY tbl_Locations.Unit_Code, tbl_Locations.Plot_ID, tbl_Events.Start_Date, "
    "tbl_LP_Belt_Transect.Transect, IIf([tlu_NCPN_Plants]![LU_Code] Is Null,[tbl_LP_S"
    "hrub]![Species],[tlu_NCPN_Plants]![LU_Code]);\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
dbText "Filter" ="[Unit_Code]='CEBR' AND [Plot_ID]=133"
Begin
End
